name: AtMos
version: ${project.version}
main: me.cojam.atmos.AtMos
api-version: 1.19
description: "Atmospheric sounds for server"
commands:
  atmosplay:
    description: "play test sound"
    usage: "/atmosplay"
  atmosvol:
    description: "Set volume for atmospheric sounds"
    usage: "/atmosvol <float>"
